apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-sonar-cm
  #namespace: sonar
  labels:
    app: postgres-sonar
data:
  POSTGRESQL_USERNAME: sonar_user
  POSTGRESQL_DATABASE: sonar_db
  POSTGRESQL_PASSWORD: S0N4RQUB3