apiVersion: v1
kind: Service
metadata:
  name: postgres-sonar-service
  #namespace: sonar
  labels:
    app: postgres-sonar
spec:
  ports:
  - port: 5432
    name: postgres
  selector:
    app: postgres-sonar